### ISSUE TITLE
dxl_reacher sensor_dt time exceeded

### ISSUE THREAD

**Issue by csherstan** [kindredresearch/SenseAct#13]
I've got an MX64AT connected and running using the dxl_reacher.py script. The motor is configured to 1000000 Baud and I've set the Return Delay Time to zero as per: https://github.com/kindredresearch/SenseAct/blob/master/senseact/devices/dxl/README.md

I'm continually getting these warnings:
Warning: Iteration time exceeded sensor_dt 10.0ms by 22.915592193603512ms

Bumping gripper_dt up gets rid of the warnings, but I'm not sure if that's a good thing.

**Comment by armahmood** [comment]
No repeat of this issue.
